spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/permissiondb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false

  logging:
    level:
      org:
        springframework:
          cache: TRACE

  data:
    redis:
      host: localhost
      port: 6379

security:
  jwt:
    secret: guvenli-super-uzun-secret-key-123456789-abcdef-xyz-123456
    expiration: 3600000

server:
  port: 8081

springdoc:
  swagger-ui:
  api-docs:
    path: /v3/api-docs

