spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/permissiondb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs
